#!/usr/bin/env bash
# Configures NGINX to run as user nginx instead of root
pkill nginx

chown nginx:nginx /etc/nginx/nginx.conf

chmod 700 /etc/nginx/nginx.conf

sed -i 's/80/8080/' /etc/nginx/sites-enabled/default

pkill apache2

sudo -u nginx service nginx start
