#!/usr/bin/env bash
# Kill gunicorn worker processe gracefully, with no downtime
# pkill -s HUP gunicorn
master_pid=$(ps -ef | grep gunicorn | grep master | awk '{print $2}')
if [ -z "$master_pid" ]; then
  echo "Gunicorn master process is not running."
  exit 1
fi
kill -HUP "$master_pid"
sleep 5
new_worker_pids=$(ps -ef | grep gunicorn | grep worker | awk '{print $2}')
old_worker_pids=$(ps -ef | grep gunicorn | grep worker | grep -v "$new_worker_pids" | awk '{print $2}')
for old_worker_pid in $old_worker_pids; do
  kill -9 "$old_worker_pid"
done
echo "Gunicorn reload complete."
